version: '3.9'

services:
  db_psql:
    image: postgres
    env_file:
      - .env
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/root
    ports:
      - "8000:8000"
    depends_on:
      - db_psql
    env_file:
      - .env