# Generated by Django 4.2.11 on 2024-05-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_photo'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_last_sumo_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(through='teams.TeamParticipant', to='teams.participant'),
        ),
        migrations.AddField(
            model_name='team',
            name='round_robin_total',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='second_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_second_subcategory', to='games.subcategory'),
        ),
        migrations.AddField(
            model_name='team',
            name='sumo_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Group'), (2, 'Second group'), (3, 'Third group')], null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sumo_total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_subcategory', to='games.subcategory'),
        ),
        migrations.CreateModel(
            name='TimeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.FloatField(default=0.0)),
                ('second_time', models.FloatField(default=0.0)),
                ('third_time', models.FloatField(default=0.0)),
                ('least_time', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.subcategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='RoundRobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.PositiveIntegerField(default=0)),
                ('score_team2', models.PositiveIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_match', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_match', to='teams.team')),
            ],
        ),
    ]
