# Generated by Django 4.2.11 on 2024-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(through='teams.TeamParticipant', to='teams.participant'),
        ),
    ]
