# Generated by Django 5.0.4 on 2024-05-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0003_team_is_active_team_is_arrived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_score', models.FloatField(default=0.0)),
                ('second_score', models.FloatField(default=0.0)),
                ('third_score', models.FloatField(default=0.0)),
                ('total_time', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.subcategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
