# Generated by Django 5.0.4 on 2024-05-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_timecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecount',
            old_name='first_score',
            new_name='first_time',
        ),
        migrations.RenameField(
            model_name='timecount',
            old_name='second_score',
            new_name='least_time',
        ),
        migrations.RenameField(
            model_name='timecount',
            old_name='third_score',
            new_name='second_time',
        ),
        migrations.RenameField(
            model_name='timecount',
            old_name='total_time',
            new_name='third_time',
        ),
    ]
