# Generated by Django 5.0.4 on 2024-05-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_first_score_timecount_first_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='round_robin_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoundRobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.IntegerField(default=0)),
                ('score_team2', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_match', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_match', to='teams.team')),
            ],
        ),
    ]
