# Generated by Django 4.2.11 on 2024-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_round_robin_total_roundrobin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundrobin',
            name='score_team1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roundrobin',
            name='score_team2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
