# Generated by Django 4.2.11 on 2024-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_photo'),
        ('teams', '0007_alter_roundrobin_score_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timecount',
            unique_together={('team', 'game')},
        ),
    ]
