# Generated by Django 5.0.4 on 2024-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_photo'),
        ('teams', '0007_alter_roundrobin_score_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sumo_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Group'), (2, 'Second group'), (3, 'Third group')], null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='round_robin_total',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='timecount',
            unique_together={('team', 'game')},
        ),
    ]
