# Generated by Django 5.0.4 on 2024-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_sumo_group_alter_team_round_robin_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sumo_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 2)], null=True),
        ),
    ]
