# Generated by Django 5.0.4 on 2024-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_sumo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sumo_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Group'), (2, 'Second group'), (3, 'Third group')], null=True),
        ),
    ]
