# Generated by Django 5.0.4 on 2024-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_team_sumo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sumo_total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
