# Generated by Django 5.0.4 on 2024-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_sumo_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_last_sumo_game',
            field=models.BooleanField(default=False),
        ),
    ]
