# Generated by Django 4.2.11 on 2024-05-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_participant_last_name_and_more'),
        ('teams', '0012_team_is_last_sumo_game'),
    ]

    operations = [
    ]
