# Generated by Django 4.2.11 on 2024-05-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_photo'),
        ('teams', '0013_merge_20240509_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timecount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='second_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_second_subcategory', to='games.subcategory'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_subcategory', to='games.subcategory'),
        ),
    ]
